# These are the funding platforms that will be used for this project

github: [abx15]
patreon: abx15
open_collective: intelligent-resource-allocation
ko_fi: abx15
tidelift: npm/resource-allocation
community_bridge: intelligent-resource-allocation
liberapay: abx15
issuehunt: abx15
otechie: abx15
custom: ["https://www.buymeacoffee.com/abx15", "https://paypal.me/abx15"]
